### ISSUE TITLE
FPS and RTF

### ISSUE THREAD

**Issue by bsb808** [salgado/vrx-awsrobomaker#1]
Very cool demo.  I'm working out AWS access through work, but I'm going to give it a try.

We noticed that the FPS and RTF in your screenshot are low.  Is it possible to run this on an instance with more CPU/GPU resources to get better performance?

**Comment by salgado** [comment]
Hi, yes is it possible.
I will include the steps for it as optional. But it's only change the EC2 instance to use a GPU. Just remeber, more resource, more money to pay for it.
